pipeline {
  agent any 
    stages {
        stage('Checkout'){
            steps{
                 echo "Getting code from Github...."
                 git branch: 'master', url:'https://github.com/palwalun/simple-java-maven-app.git'
                 }
              }
        stage('Build'){
           steps{
               echo "Building the code..."
               sh "mvn clean package"
                }
             }
        stage('Build & Deploy Docker Image'){
            steps{
               sh "docker build -t palwalun/jenkins-image:v1.0 ."
                sh "docker run -d --name jenkins-build -p 8089:8080 palwalun/jenkins-image:v1.0"
            }
        }
  
    }
    
}
